### ISSUE TITLE
Multiple return values not allowed in R

### ISSUE THREAD

**Issue by trevorki** [UBC-MDS/kmeaningfulR#16]
For the `fit_assign()` function in python we had it return a the centers and the labels as 2 objects. R doesn't allow that. I can think of 2 workarounds:

1. Return a list that contains the two objects. It would make using the function clunkier though. I suppose we could just pass the list into `show_clusters()`. Clunky in a different way.
2. Just ditch the `fit_assign()` funtion altogether and only allow separate `fit()` and `assign()` calls. This is the lazy solution.

What are your thoughts?

**Comment by mikelynch416** [comment]
I don't have a strong opinion either way but I think your proposed workaround 1 follows the convention in R for functions with multiple returns - I wouldn't call it a clunky solution that's just how R is.

**Comment by trevorki** [comment]
Ok, I'll go with returning a list then
