### ISSUE TITLE
Test installation

### ISSUE THREAD

**Issue by sbabicki** [UBC-MDS/kmeaningfulR#27]
Test that functions can be run successfully in new environment by following instructions in README of this repo. 

By the end of this milestone, we should be able to install and use your R package functions from GitHub (you are not expected to publish your package on CRAN during this course, just GitHub).

**Comment by trevorki** [comment]
I did this and encountered a problem as described in this issue: https://github.com/UBC-MDS/kmeaningfulR/issues/34
After changing the output of preprocess to a matrix everything works beautifully!

**Comment by sbabicki** [comment]
Thank you! Are we good to close this one then?
