### ISSUE TITLE
GitHub actions workflow for continuous integration

### ISSUE THREAD

**Issue by sbabicki** [UBC-MDS/kmeaningfulR#39]
rubric={mechanics:35}

Your task here is to add continuous integration workflows using GitHub Actions for running R CMD check and your tests and sending the results to https://codecov.io/. In particular, you want to use the usethis package functions to add the following two workflows to your project:

https://github.com/r-lib/actions/blob/master/.github/workflows/check-standard.yaml

https://github.com/r-lib/actions/blob/master/.github/workflows/test-coverage.yaml

At time of submission, we expect that your project successfully runs these workflows.

**Comment by trevorki** [comment]
This is now complete, but I had to modify R-CMD-check.yaml to prevent an error in an automated check on windows.
See this issue:
https://github.com/UBC-MDS/kmeaningfulR/issues/49#issue-836194092
