### ISSUE TITLE
Initiate a package review request

### ISSUE THREAD

**Issue by sbabicki** [UBC-MDS/kmeaningfulR#42]
rubric={mechanics:10}

Each team must initiate a review request by opening an issue per package in the [UBC-MDS/software-review-2021 repository](https://github.com/UBC-MDS/software-review-2021).

For initiating a reviewing request in R, use [this template](https://devguide.ropensci.org/reviewrequesttemplate.html).

For initiating a reviewing request in Python, use the template under Submit Software for Review [at this link](https://github.com/pyOpenSci/software-review/issues/new/choose).

**Comment by sbabicki** [comment]
Link Tiff put in the chat in lab:
https://github.com/ropensci/software-review/issues/new?assignees=&labels=&template=A-submit-software-for-review.md

**Comment by HazelJJJ** [comment]
Package review created for Python: https://github.com/UBC-MDS/software-review-2021/issues/33
Package review created for R: https://github.com/UBC-MDS/software-review-2021/issues/34

**Comment by sbabicki** [comment]
@HazelJJJ thanks for doing this! Can the issue be closed now?

**Comment by sbabicki** [comment]
@HazelJJJ I'm going to close it, if it's still outstanding feel free to reopen it!
